language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf-archive
before_script:
  - autoconf -V
  - uname -a
  - lsb_release -a
  - dpkg -l | grep auto
script: ./autogen.sh && ./configure && make && make test
