language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf-archive gnulib docbook2x ncurses-dev
script: autoreconf -i -I/usr/share/gnulib/m4 && ./configure && make && make test
