language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf-archive gnulib docbook2x ncurses-dev
  - : > ChangeLog
script: autoreconf -i -I/usr/share/gnulib/m4 && CFLAGS="-Wall -Wextra" ./configure && make distcheck
