language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf-archive gnulib
before_script:
  - autoconf -V
  - uname -a
  - lsb_release -a
  - dpkg -l | grep auto
script: autoreconf -i -I/usr/share/gnulib/m4 && ./configure && make && make test
